package me.goosemonkey.Scores;

/**
 * Stores scores
 */
public class ConfigScores extends ConfigAbstract
{
	public ConfigScores(Scores inst)
	{
		super(inst);
	}

	@Override
	public String getHeader()
	{
		return "This file holds the scores of all players on a server.\n" +
				"Do not edit this file while the server is running!";
	}

	@Override
	public String getName()
	{
		return "ScoresData.yml";
	}

	@Override
	public void setDefaultValues()
	{
		
	}
}
